package dendrite_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sivchari/dendrite/internal/config"
	"github.com/sivchari/dendrite/internal/generator"
	"github.com/sivchari/dendrite/internal/lock"
	"github.com/sivchari/dendrite/internal/platform"
)

// toolName reconstructs the "owner/repo@version" identifier from a parsed Tool.
func toolName(t *config.Tool) string {
	return t.Owner + "/" + t.Repo + "@" + t.Version
}

// writeFile is a test helper that writes content to path, creating parent directories.
func writeFile(t *testing.T, path, content string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatalf("failed to create directory for %s: %v", path, err)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write %s: %v", path, err)
	}
}

// generateFromConfigAndLock runs the full pipeline: parse config, lookup lock entries,
// and generate nix files. This mirrors the logic in cmd/dendrite/main.go runGenerate.
func generateFromConfigAndLock(t *testing.T, configPath, lockPath, outDir string, p platform.Platform) {
	t.Helper()

	cfg, err := config.Parse(configPath)
	if err != nil {
		t.Fatalf("config.Parse failed: %v", err)
	}

	pKey := lock.PlatformKey(p)

	lf, err := lock.Read(lockPath)
	if err != nil {
		t.Fatalf("lock.Read failed: %v", err)
	}

	var inputs []generator.GenerateInput

	for i := range cfg.Tools {
		name := toolName(&cfg.Tools[i])

		entry := lock.Lookup(lf, name, pKey)
		if entry == nil {
			t.Fatalf("no lock entry found for %s on platform %s", name, pKey)
		}

		inputs = append(inputs, generator.GenerateInput{
			Tool: cfg.Tools[i],
			Lock: generator.LockEntry{
				URL:    entry.URL,
				SHA256: entry.SHA256,
			},
		})
	}

	if err := generator.GenerateAll(inputs, outDir); err != nil {
		t.Fatalf("generator.GenerateAll failed: %v", err)
	}
}

// assertFileExists checks that the file at path exists.
func assertFileExists(t *testing.T, path string) {
	t.Helper()

	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Fatalf("expected file to exist: %s", path)
	}
}

// assertContains checks that content contains the given substring.
func assertContains(t *testing.T, content, substr, ctx string) {
	t.Helper()

	if !strings.Contains(content, substr) {
		t.Errorf("%s: expected content to contain %q, but it was not found.\nFull content:\n%s", ctx, substr, content)
	}
}

// assertNotContains checks that content does not contain the given substring.
func assertNotContains(t *testing.T, content, substr, ctx string) {
	t.Helper()

	if strings.Contains(content, substr) {
		t.Errorf("%s: expected content NOT to contain %q, but it was found.\nFull content:\n%s", ctx, substr, content)
	}
}

// --- Test 1: Full pipeline test ---

func TestE2E_FullPipeline(t *testing.T) { //nolint:funlen // e2e test with comprehensive verification
	t.Parallel()

	tmpDir := t.TempDir()

	configPath := filepath.Join(tmpDir, "dendrite.yaml")
	lockPath := filepath.Join(tmpDir, "dendrite.lock.yaml")
	outDir := filepath.Join(tmpDir, "packages")

	configContent := `tools:
  - name: cli/cli@v2.87.0
    asset: gh_{version}_{os}_{arch}.tar.gz
    bins:
      - gh
  - name: BurntSushi/ripgrep@14.1.0
    asset: ripgrep-{version}-{arch}-{os}.tar.gz
    bins:
      - rg
`

	lockContent := `# Auto-generated by dendrite. Do not edit.
tools:
    - name: cli/cli@v2.87.0
      assets:
        darwin_arm64:
            url: "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_macOS_arm64.tar.gz"
            sha256: "sha256-abc123fakehashGH="
    - name: BurntSushi/ripgrep@14.1.0
      assets:
        darwin_arm64:
            url: "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-aarch64-darwin.tar.gz"
            sha256: "sha256-xyz789fakehashRG="
`

	writeFile(t, configPath, configContent)
	writeFile(t, lockPath, lockContent)

	generateFromConfigAndLock(t, configPath, lockPath, outDir, platform.DarwinARM64)

	tests := []struct {
		name    string
		nixPath string
		pname   string
		version string
		url     string
		sha256  string
		bins    []string
	}{
		{
			name:    "cli",
			nixPath: filepath.Join(outDir, "cli", "default.nix"),
			pname:   "cli",
			version: "2.87.0",
			url:     "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_macOS_arm64.tar.gz",
			sha256:  "sha256-abc123fakehashGH=",
			bins:    []string{"gh"},
		},
		{
			name:    "ripgrep",
			nixPath: filepath.Join(outDir, "ripgrep", "default.nix"),
			pname:   "ripgrep",
			version: "14.1.0",
			url:     "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-aarch64-darwin.tar.gz",
			sha256:  "sha256-xyz789fakehashRG=",
			bins:    []string{"rg"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			// (a) File exists at correct path.
			assertFileExists(t, tt.nixPath)

			content, err := os.ReadFile(tt.nixPath)
			if err != nil {
				t.Fatalf("failed to read %s: %v", tt.nixPath, err)
			}

			nix := string(content)

			// (b) Contains correct pname, version (no v prefix).
			assertContains(t, nix, `pname = "`+tt.pname+`"`, "pname")
			assertContains(t, nix, `version = "`+tt.version+`"`, "version")
			assertNotContains(t, nix, `version = "v`, "version should not have v prefix")

			// (c) Contains correct fetchurl URL and sha256.
			assertContains(t, nix, `url = "`+tt.url+`"`, "url")
			assertContains(t, nix, `sha256 = "`+tt.sha256+`"`, "sha256")

			// (d) Contains correct bin names in installPhase.
			for _, bin := range tt.bins {
				assertContains(t, nix, `chmod +x $out/bin/`+bin, "bin in installPhase")
			}

			// (e) Has valid Nix syntax structure.
			assertContains(t, nix, "stdenv,", "nix function arg stdenv")
			assertContains(t, nix, "fetchurl,", "nix function arg fetchurl")
			assertContains(t, nix, "stdenv.mkDerivation rec {", "mkDerivation")
			assertContains(t, nix, "src = fetchurl {", "fetchurl block")
			assertContains(t, nix, "dontUnpack = true;", "dontUnpack")
			assertContains(t, nix, "installPhase = ''", "installPhase")
			assertContains(t, nix, "mkdir -p $out/bin", "mkdir in installPhase")
			assertContains(t, nix, "tar -xzf $src -C $out/bin", "tar in installPhase")
		})
	}
}

// --- Test 2: Multiple tools with different configurations ---

func TestE2E_MultipleToolConfigurations(t *testing.T) { //nolint:funlen // e2e test with many configuration variants
	t.Parallel()

	tests := []struct {
		name            string
		configYAML      string
		lockToolName    string
		lockURL         string
		lockSHA256      string
		expectedPname   string
		expectedVersion string
		expectedBins    []string
		expectedDir     string // directory name under packages/
	}{
		{
			name: "explicit bins",
			configYAML: `tools:
  - name: cli/cli@v2.87.0
    asset: gh_{version}_{os}_{arch}.tar.gz
    bins:
      - gh
`,
			lockToolName:    "cli/cli@v2.87.0",
			lockURL:         "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_darwin_arm64.tar.gz",
			lockSHA256:      "sha256-explicithash=",
			expectedPname:   "cli",
			expectedVersion: "2.87.0",
			expectedBins:    []string{"gh"},
			expectedDir:     "cli",
		},
		{
			name: "default bins from repo name",
			configYAML: `tools:
  - name: aquaproj/aqua@v2.39.0
    asset: aqua_{os}_{arch}.tar.gz
`,
			lockToolName:    "aquaproj/aqua@v2.39.0",
			lockURL:         "https://github.com/aquaproj/aqua/releases/download/v2.39.0/aqua_darwin_arm64.tar.gz",
			lockSHA256:      "sha256-defaultbinhash=",
			expectedPname:   "aqua",
			expectedVersion: "2.39.0",
			expectedBins:    []string{"aqua"},
			expectedDir:     "aqua",
		},
		{
			name: "version with v prefix",
			configYAML: `tools:
  - name: sharkdp/bat@v0.24.0
    asset: bat-v{version}-{arch}-{os}.tar.gz
    bins:
      - bat
`,
			lockToolName:    "sharkdp/bat@v0.24.0",
			lockURL:         "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-arm64-darwin.tar.gz",
			lockSHA256:      "sha256-vprefixhash=",
			expectedPname:   "bat",
			expectedVersion: "0.24.0",
			expectedBins:    []string{"bat"},
			expectedDir:     "bat",
		},
		{
			name: "version without v prefix",
			configYAML: `tools:
  - name: BurntSushi/ripgrep@14.1.0
    asset: ripgrep-{version}-{arch}-{os}.tar.gz
    bins:
      - rg
`,
			lockToolName:    "BurntSushi/ripgrep@14.1.0",
			lockURL:         "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-arm64-darwin.tar.gz",
			lockSHA256:      "sha256-novprefixhash=",
			expectedPname:   "ripgrep",
			expectedVersion: "14.1.0",
			expectedBins:    []string{"rg"},
			expectedDir:     "ripgrep",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			tmpDir := t.TempDir()

			configPath := filepath.Join(tmpDir, "dendrite.yaml")
			lockPath := filepath.Join(tmpDir, "dendrite.lock.yaml")
			outDir := filepath.Join(tmpDir, "packages")

			writeFile(t, configPath, tt.configYAML)

			lockContent := "# Auto-generated by dendrite. Do not edit.\ntools:\n" +
				"    - name: " + tt.lockToolName + "\n" +
				"      assets:\n" +
				"        darwin_arm64:\n" +
				"            url: \"" + tt.lockURL + "\"\n" +
				"            sha256: \"" + tt.lockSHA256 + "\"\n"
			writeFile(t, lockPath, lockContent)

			generateFromConfigAndLock(t, configPath, lockPath, outDir, platform.DarwinARM64)

			nixPath := filepath.Join(outDir, tt.expectedDir, "default.nix")
			assertFileExists(t, nixPath)

			content, err := os.ReadFile(nixPath)
			if err != nil {
				t.Fatalf("failed to read %s: %v", nixPath, err)
			}

			nix := string(content)

			assertContains(t, nix, `pname = "`+tt.expectedPname+`"`, "pname")
			assertContains(t, nix, `version = "`+tt.expectedVersion+`"`, "version")
			assertNotContains(t, nix, `version = "v`, "version should not have v prefix")
			assertContains(t, nix, `url = "`+tt.lockURL+`"`, "url")
			assertContains(t, nix, `sha256 = "`+tt.lockSHA256+`"`, "sha256")

			for _, bin := range tt.expectedBins {
				assertContains(t, nix, `chmod +x $out/bin/`+bin, "bin in installPhase")
			}
		})
	}
}

// --- Test 4: Lock file round-trip ---

func TestE2E_LockFileRoundTrip(t *testing.T) { //nolint:funlen,gocognit // e2e round-trip verification
	t.Parallel()

	tmpDir := t.TempDir()
	lockPath := filepath.Join(tmpDir, "dendrite.lock.yaml")

	original := &lock.LockFile{
		Tools: []lock.ToolLock{
			{
				Name: "cli/cli@v2.87.0",
				Assets: map[string]lock.AssetLock{
					"darwin_arm64": {
						URL:    "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_macOS_arm64.tar.gz",
						SHA256: "sha256-abc123=",
					},
					"linux_amd64": {
						URL:    "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_linux_amd64.tar.gz",
						SHA256: "sha256-def456=",
					},
				},
			},
			{
				Name: "aquaproj/aqua@v2.39.0",
				Assets: map[string]lock.AssetLock{
					"darwin_arm64": {
						URL:    "https://github.com/aquaproj/aqua/releases/download/v2.39.0/aqua_darwin_arm64.tar.gz",
						SHA256: "sha256-ghi789=",
					},
				},
			},
		},
	}

	// Write the lock file
	if err := lock.Write(lockPath, original); err != nil {
		t.Fatalf("lock.Write failed: %v", err)
	}

	// Verify the file exists
	assertFileExists(t, lockPath)

	// Read it back
	roundTripped, err := lock.Read(lockPath)
	if err != nil {
		t.Fatalf("lock.Read failed: %v", err)
	}

	// Verify all entries are preserved.
	if len(roundTripped.Tools) != len(original.Tools) {
		t.Fatalf("expected %d tools, got %d", len(original.Tools), len(roundTripped.Tools))
	}

	for _, origTool := range original.Tools {
		found := false

		for _, rtTool := range roundTripped.Tools {
			if rtTool.Name != origTool.Name {
				continue
			}

			found = true

			if len(rtTool.Assets) != len(origTool.Assets) {
				t.Errorf("tool %s: expected %d assets, got %d", origTool.Name, len(origTool.Assets), len(rtTool.Assets))

				continue
			}

			for pKey, origAsset := range origTool.Assets {
				rtAsset, ok := rtTool.Assets[pKey]
				if !ok {
					t.Errorf("tool %s: missing platform %s after round-trip", origTool.Name, pKey)

					continue
				}

				if rtAsset.URL != origAsset.URL {
					t.Errorf("tool %s platform %s: URL mismatch: got %q, want %q", origTool.Name, pKey, rtAsset.URL, origAsset.URL)
				}

				if rtAsset.SHA256 != origAsset.SHA256 {
					t.Errorf("tool %s platform %s: SHA256 mismatch: got %q, want %q", origTool.Name, pKey, rtAsset.SHA256, origAsset.SHA256)
				}
			}

			break
		}

		if !found {
			t.Errorf("tool %s not found after round-trip", origTool.Name)
		}
	}

	// Also verify we can do Lookup on the round-tripped data.
	entry := lock.Lookup(roundTripped, "cli/cli@v2.87.0", "darwin_arm64")
	if entry == nil {
		t.Fatal("Lookup returned nil for cli/cli@v2.87.0 on darwin_arm64")
	}

	if entry.SHA256 != "sha256-abc123=" {
		t.Errorf("Lookup SHA256 mismatch: got %q, want %q", entry.SHA256, "sha256-abc123=")
	}

	entry = lock.Lookup(roundTripped, "cli/cli@v2.87.0", "linux_amd64")
	if entry == nil {
		t.Fatal("Lookup returned nil for cli/cli@v2.87.0 on linux_amd64")
	}

	if entry.URL != "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_linux_amd64.tar.gz" {
		t.Errorf("Lookup URL mismatch: got %q", entry.URL)
	}
}

// --- Test 5: Error cases ---

func TestE2E_ErrorCases(t *testing.T) { //nolint:funlen // e2e error case test
	t.Parallel()

	t.Run("generate without lock file", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()

		configPath := filepath.Join(tmpDir, "dendrite.yaml")
		lockPath := filepath.Join(tmpDir, "dendrite.lock.yaml")

		configContent := `tools:
  - name: cli/cli@v2.87.0
    asset: gh_{version}_{os}_{arch}.tar.gz
    bins:
      - gh
`
		writeFile(t, configPath, configContent)
		// Intentionally do NOT create the lock file.

		cfg, err := config.Parse(configPath)
		if err != nil {
			t.Fatalf("config.Parse failed: %v", err)
		}

		_ = cfg

		_, err = lock.Read(lockPath)
		if err == nil {
			t.Fatal("expected error when reading non-existent lock file, got nil")
		}

		if !strings.Contains(err.Error(), "failed to read lock file") {
			t.Errorf("expected error message to contain 'failed to read lock file', got: %v", err)
		}
	})

	t.Run("lock file missing entry for a tool", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()

		configPath := filepath.Join(tmpDir, "dendrite.yaml")
		lockPath := filepath.Join(tmpDir, "dendrite.lock.yaml")

		// Config has two tools.
		configContent := `tools:
  - name: cli/cli@v2.87.0
    asset: gh_{version}_{os}_{arch}.tar.gz
    bins:
      - gh
  - name: BurntSushi/ripgrep@14.1.0
    asset: ripgrep-{version}-{arch}-{os}.tar.gz
    bins:
      - rg
`
		// Lock file only has one tool (missing ripgrep).
		lockContent := `# Auto-generated by dendrite. Do not edit.
tools:
    - name: cli/cli@v2.87.0
      assets:
        darwin_arm64:
            url: "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_macOS_arm64.tar.gz"
            sha256: "sha256-fakehash="
`
		writeFile(t, configPath, configContent)
		writeFile(t, lockPath, lockContent)

		cfg, err := config.Parse(configPath)
		if err != nil {
			t.Fatalf("config.Parse failed: %v", err)
		}

		pKey := lock.PlatformKey(platform.DarwinARM64)

		lf, err := lock.Read(lockPath)
		if err != nil {
			t.Fatalf("lock.Read failed: %v", err)
		}

		// Verify the first tool is found.
		entry := lock.Lookup(lf, "cli/cli@v2.87.0", pKey)
		if entry == nil {
			t.Fatal("expected lock entry for cli/cli@v2.87.0 to exist")
		}

		// Verify the second tool is NOT found.
		missingEntry := lock.Lookup(lf, toolName(&cfg.Tools[1]), pKey)
		if missingEntry != nil {
			t.Fatal("expected lock entry for BurntSushi/ripgrep@14.1.0 to be nil, but got a value")
		}
	})

	t.Run("lock file missing platform for existing tool", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()
		lockPath := filepath.Join(tmpDir, "dendrite.lock.yaml")

		lockContent := `# Auto-generated by dendrite. Do not edit.
tools:
    - name: cli/cli@v2.87.0
      assets:
        darwin_arm64:
            url: "https://github.com/cli/cli/releases/download/v2.87.0/gh_2.87.0_macOS_arm64.tar.gz"
            sha256: "sha256-fakehash="
`
		writeFile(t, lockPath, lockContent)

		lf, err := lock.Read(lockPath)
		if err != nil {
			t.Fatalf("lock.Read failed: %v", err)
		}

		// Tool exists but platform does not.
		entry := lock.Lookup(lf, "cli/cli@v2.87.0", "linux_amd64")
		if entry != nil {
			t.Fatal("expected nil for non-existent platform, got a value")
		}
	})
}

// --- Test: Verify lock file header is preserved ---

func TestE2E_LockFileHeader(t *testing.T) { //nolint:funlen // e2e header verification test
	t.Parallel()

	tmpDir := t.TempDir()
	lockPath := filepath.Join(tmpDir, "dendrite.lock.yaml")

	lf := &lock.LockFile{
		Tools: []lock.ToolLock{
			{
				Name: "test/tool@v1.0.0",
				Assets: map[string]lock.AssetLock{
					"darwin_arm64": {
						URL:    "https://example.com/tool.tar.gz",
						SHA256: "sha256-test=",
					},
				},
			},
		},
	}

	if err := lock.Write(lockPath, lf); err != nil {
		t.Fatalf("lock.Write failed: %v", err)
	}

	content, err := os.ReadFile(lockPath)
	if err != nil {
		t.Fatalf("failed to read lock file: %v", err)
	}

	if !strings.HasPrefix(string(content), "# Auto-generated by dendrite. Do not edit.") {
		t.Errorf("lock file should start with header comment, got:\n%s", string(content)[:100]) //nolint:gocritic // slicing for display is intentional
	}
}
