// Package lock handles reading, writing, and querying the dendrite lock file
// (dendrite.lock.yaml), as well as computing SHA256 hashes via nix-prefetch-url
// (public tools) or the GitHub API (private tools).
package lock

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/sivchari/dendrite/internal/platform"
)

// defaultGitHubAPIBaseURL is the production GitHub REST API base URL.
const defaultGitHubAPIBaseURL = "https://api.github.com"

// lockFileHeader is prepended to every generated lock file.
const lockFileHeader = "# Code generated by dendrite; DO NOT EDIT.\n"

// File represents the top-level structure of dendrite.lock.yaml.
type File struct {
	Tools []ToolLock `yaml:"tools"`
}

// ToolLock represents a single tool entry in the lock file.
type ToolLock struct {
	Name   string               `yaml:"name"`
	Assets map[string]AssetLock `yaml:"assets"` // key: "darwin_arm64", "linux_amd64", etc.
}

// AssetLock holds the URL and SHA256 hash for a specific platform asset.
// AssetID is populated only for assets resolved from a private repository,
// since generate needs it to build the authenticated GitHub API download URL.
type AssetLock struct {
	URL     string `yaml:"url"`
	SHA256  string `yaml:"sha256"`
	AssetID int64  `yaml:"asset_id,omitempty"`
}

// Read reads and parses a lock file from disk.
func Read(path string) (*File, error) {
	data, err := os.ReadFile(path) //nolint:gosec // path is from user-provided flag input
	if err != nil {
		return nil, fmt.Errorf("failed to read lock file %s: %w", path, err)
	}

	var lf File
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("failed to parse lock file %s: %w", path, err)
	}

	return &lf, nil
}

// Write serializes the lock file to disk with a header comment.
func Write(path string, lock *File) error {
	data, err := yaml.Marshal(lock)
	if err != nil {
		return fmt.Errorf("failed to marshal lock file: %w", err)
	}

	content := lockFileHeader + string(data)

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("failed to write lock file %s: %w", path, err)
	}

	return nil
}

// Lookup finds the AssetLock for a given tool name and platform key.
// Returns nil if no matching entry is found.
func Lookup(lock *File, name, platformKey string) *AssetLock {
	for i := range lock.Tools {
		if lock.Tools[i].Name == name {
			if asset, ok := lock.Tools[i].Assets[platformKey]; ok {
				return &asset
			}

			return nil
		}
	}

	return nil
}

// PrefetchURL runs nix-prefetch-url to compute the SHA256 hash of the given
// URL. The returned hash is in SRI format: "sha256-<base64>".
func PrefetchURL(url string) (string, error) {
	prefetch := exec.Command("nix-prefetch-url", "--type", "sha256", url) //nolint:noctx // no context available in this utility function

	out, err := prefetch.Output()
	if err != nil {
		return "", fmt.Errorf("nix-prefetch-url failed for %s: %w", url, err)
	}

	nix32Hash := strings.TrimSpace(string(out))

	convert := exec.Command("nix", "hash", "convert", "--hash-algo", "sha256", "--to", "sri", nix32Hash) //nolint:gosec,noctx // nix32Hash is output from nix-prefetch-url; no context available

	sri, err := convert.Output()
	if err != nil {
		return "", fmt.Errorf("nix hash convert failed for %q: %w", nix32Hash, err)
	}

	return strings.TrimSpace(string(sri)), nil
}

// PlatformKey returns the lock file key for a given platform,
// e.g. "darwin_arm64" or "linux_amd64".
func PlatformKey(p platform.Platform) string {
	return p.OS + "_" + p.Arch
}

// Token resolves a GitHub API token for authenticating private repository
// requests, checking GITHUB_TOKEN first and falling back to GH_TOKEN.
func Token() (string, error) {
	if token := os.Getenv("GITHUB_TOKEN"); token != "" {
		return token, nil
	}

	if token := os.Getenv("GH_TOKEN"); token != "" {
		return token, nil
	}

	return "", fmt.Errorf("private tool requires a GitHub token: set GITHUB_TOKEN or GH_TOKEN")
}

// PrivateAssetURL builds the authenticated GitHub API URL for downloading a
// specific release asset by ID. This is the URL stored in the lock file and
// embedded in generated Nix derivations for private tools.
func PrivateAssetURL(owner, repo string, assetID int64) string {
	return fmt.Sprintf("%s/repos/%s/%s/releases/assets/%d", defaultGitHubAPIBaseURL, owner, repo, assetID)
}

// githubReleaseAsset is the subset of the GitHub release asset API response
// dendrite needs.
type githubReleaseAsset struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// githubRelease is the subset of the GitHub release API response dendrite needs.
type githubRelease struct {
	Assets []githubReleaseAsset `json:"assets"`
}

// FetchPrivateAsset resolves a release asset by filename in a private GitHub
// repository, downloads its content, and returns the asset ID and an
// SRI-formatted SHA256 hash ("sha256-<base64>"). tag may contain "/" (e.g.
// "haro-cli/v0.3.1"); it is percent-encoded before being sent to the API.
func FetchPrivateAsset(ctx context.Context, client *http.Client, owner, repo, tag, assetName, token string) (int64, string, error) {
	return fetchPrivateAsset(ctx, client, defaultGitHubAPIBaseURL, owner, repo, tag, assetName, token)
}

// fetchPrivateAsset is the baseURL-parameterized implementation of
// FetchPrivateAsset, allowing tests to point at an httptest.Server.
func fetchPrivateAsset(ctx context.Context, client *http.Client, baseURL, owner, repo, tag, assetName, token string) (int64, string, error) {
	rel, err := getReleaseByTag(ctx, client, baseURL, owner, repo, tag, token)
	if err != nil {
		return 0, "", err
	}

	assetID, err := findAssetID(rel, assetName)
	if err != nil {
		return 0, "", fmt.Errorf("failed to resolve asset for %s/%s@%s: %w", owner, repo, tag, err)
	}

	data, err := downloadAsset(ctx, client, baseURL, owner, repo, assetID, token)
	if err != nil {
		return 0, "", err
	}

	return assetID, hashSRI(data), nil
}

// getReleaseByTag fetches release metadata (including its asset list) for a
// given repository and tag from the GitHub API.
func getReleaseByTag(ctx context.Context, client *http.Client, baseURL, owner, repo, tag, token string) (*githubRelease, error) {
	releaseURL := fmt.Sprintf("%s/repos/%s/%s/releases/tags/%s", baseURL, owner, repo, url.PathEscape(tag))

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, releaseURL, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("failed to build release request for %s/%s@%s: %w", owner, repo, tag, err)
	}

	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch release %s/%s@%s: %w", owner, repo, tag, err)
	}

	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("failed to fetch release %s/%s@%s: unexpected status %s", owner, repo, tag, resp.Status)
	}

	var rel githubRelease
	if err := json.NewDecoder(resp.Body).Decode(&rel); err != nil {
		return nil, fmt.Errorf("failed to decode release response for %s/%s@%s: %w", owner, repo, tag, err)
	}

	return &rel, nil
}

// findAssetID looks up an asset's numeric ID by its exact filename within a
// release's asset list.
func findAssetID(rel *githubRelease, assetName string) (int64, error) {
	for _, asset := range rel.Assets {
		if asset.Name == assetName {
			return asset.ID, nil
		}
	}

	return 0, fmt.Errorf("asset %q not found in release", assetName)
}

// downloadAsset downloads the raw content of a release asset by ID, using the
// GitHub API's octet-stream download endpoint.
func downloadAsset(ctx context.Context, client *http.Client, baseURL, owner, repo string, assetID int64, token string) ([]byte, error) {
	assetURL := fmt.Sprintf("%s/repos/%s/%s/releases/assets/%d", baseURL, owner, repo, assetID)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, assetURL, http.NoBody)
	if err != nil {
		return nil, fmt.Errorf("failed to build asset download request for asset %d: %w", assetID, err)
	}

	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/octet-stream")

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to download asset %d: %w", assetID, err)
	}

	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("failed to download asset %d: unexpected status %s", assetID, resp.Status)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read asset %d body: %w", assetID, err)
	}

	return data, nil
}

// hashSRI computes the SHA256 hash of data and formats it as an SRI string
// ("sha256-<base64>"), matching the format nix-prefetch-url / nix hash
// convert produce for public tools.
func hashSRI(data []byte) string {
	sum := sha256.Sum256(data)

	return "sha256-" + base64.StdEncoding.EncodeToString(sum[:])
}
