// Package lock handles reading, writing, and querying the dendrite lock file
// (dendrite.lock.yaml), as well as computing SHA256 hashes via nix-prefetch-url.
package lock

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/sivchari/dendrite/internal/platform"
)

// lockFileHeader is prepended to every generated lock file.
const lockFileHeader = "# Auto-generated by dendrite. Do not edit.\n"

// File represents the top-level structure of dendrite.lock.yaml.
type File struct {
	Tools []ToolLock `yaml:"tools"`
}

// ToolLock represents a single tool entry in the lock file.
type ToolLock struct {
	Name   string               `yaml:"name"`
	Assets map[string]AssetLock `yaml:"assets"` // key: "darwin_arm64", "linux_amd64", etc.
}

// AssetLock holds the URL and SHA256 hash for a specific platform asset.
type AssetLock struct {
	URL    string `yaml:"url"`
	SHA256 string `yaml:"sha256"`
}

// Read reads and parses a lock file from disk.
func Read(path string) (*File, error) {
	data, err := os.ReadFile(path) //nolint:gosec // path is from user-provided flag input
	if err != nil {
		return nil, fmt.Errorf("failed to read lock file %s: %w", path, err)
	}

	var lf File
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("failed to parse lock file %s: %w", path, err)
	}

	return &lf, nil
}

// Write serializes the lock file to disk with a header comment.
func Write(path string, lock *File) error {
	data, err := yaml.Marshal(lock)
	if err != nil {
		return fmt.Errorf("failed to marshal lock file: %w", err)
	}

	content := lockFileHeader + string(data)

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil { //nolint:gosec // lock file needs 0o644 for Nix to read it
		return fmt.Errorf("failed to write lock file %s: %w", path, err)
	}

	return nil
}

// Lookup finds the AssetLock for a given tool name and platform key.
// Returns nil if no matching entry is found.
func Lookup(lock *File, name, platformKey string) *AssetLock {
	for i := range lock.Tools {
		if lock.Tools[i].Name == name {
			if asset, ok := lock.Tools[i].Assets[platformKey]; ok {
				return &asset
			}

			return nil
		}
	}

	return nil
}

// PrefetchURL runs nix-prefetch-url to compute the SHA256 hash of the given
// URL. The returned hash is in SRI format: "sha256-<base64>".
func PrefetchURL(url string) (string, error) {
	prefetch := exec.Command("nix-prefetch-url", "--type", "sha256", url) //nolint:gosec,noctx // url is from trusted config input; no context available in this utility function
	out, err := prefetch.Output()

	if err != nil {
		return "", fmt.Errorf("nix-prefetch-url failed for %s: %w", url, err)
	}

	nix32Hash := strings.TrimSpace(string(out))

	convert := exec.Command("nix", "hash", "convert", "--hash-algo", "sha256", "--to", "sri", nix32Hash) //nolint:gosec,noctx // nix32Hash is output from nix-prefetch-url; no context available in this utility function
	sri, err := convert.Output()

	if err != nil {
		return "", fmt.Errorf("nix hash convert failed for %q: %w", nix32Hash, err)
	}

	return strings.TrimSpace(string(sri)), nil
}

// PlatformKey returns the lock file key for a given platform,
// e.g. "darwin_arm64" or "linux_amd64".
func PlatformKey(p platform.Platform) string {
	return p.OS + "_" + p.Arch
}
